
		               TekstCheck01  "Štelanje"
                       TekstCheck02  "Kraj serije"
                       TekstCheck03  "Prekid serije"
                       TekstCheck04  "Bolovanja"
                       TekstCheck05  "Rad pod pauzom"
                       TekstCheck06  "Nema djelatnika"
                       TekstCheck07  "Kvar stroja"
                       TekstCheck08  "Remont"
                       TekstCheck09  "Problem stezni alat"
                       TekstCheck10  "Problem rezni alat"
                       TekstCheck11  "Problem sa mjerama"
                       TekstCheck12  "Bez transportera"
                       TekstCheck13  "Podbaèaj"
                       TekstCheck14  "Prebaèaj"
                       TekstCheck15  "Nema sirovine"
                       TekstCheck16  "Pripomoæ"
                       TekstCheck17  "Novi nalog"
                       TekstCheck18  "Nezaplanirana"
                       TekstCheck19  "Dorada"
                       TekstCheck20  "Problem sirov.mat"