USE FeroApp

SELECT TJ.*, 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN1 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada1 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN1, '') <> '' ))) AND EPS.Status = 0), 0) + 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN2 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada2 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN2, '') <> '' ))) AND EPS.Status = 0), 0) + 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN3 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada3 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN3, '') <> '' ))) AND EPS.Status = 0), 0) + 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN4 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada4 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN4, '') <> '' ))) AND EPS.Status = 0), 0) AS Spremno, 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN1 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada1 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN1, '') <> '' ))) AND EPS.Status = 1), 0) + 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN2 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada2 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN2, '') <> '' ))) AND EPS.Status = 1), 0) + 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN3 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada3 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN3, '') <> '' ))) AND EPS.Status = 1), 0) + 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN4 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada4 = 1 AND NS1.DatumIsporuke BETWEEN TJ.PocetniDatum AND TJ.ZavrsniDatum AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN4, '') <> '' ))) AND EPS.Status = 1), 0) AS Fakturirano 
	FROM TmpJanjic TJ
		LEFT JOIN NarudzbeZag NarZ ON TJ.OrderNo = NarZ.OrderNo 
	WHERE TJ.VrstaDok = 'DI'	
UNION
SELECT TJ.*, 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN1 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada1 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN1, '') <> '' ))) AND EPS.Status = 0), 0) + ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN2 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada2 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN2, '') <> '' ))) AND EPS.Status = 0), 0) + ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN3 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada3 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN3, '') <> '' ))) AND EPS.Status = 0), 0) + ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN4 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada4 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN4, '') <> '' ))) AND EPS.Status = 0), 0) AS Spremno, 
	ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN1 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada1 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN1, '') <> '' ))) AND EPS.Status = 1), 0) + ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN2 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada2 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN2, '') <> '' ))) AND EPS.Status = 1), 0) + ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN3 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada3 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN3, '') <> '' ))) AND EPS.Status = 1), 0) + ISNULL((SELECT SUM(ISNULL(EPS.KolicinaOK, 0)) FROM EvidencijaProizvodnjeSta EPS WHERE EPS.ID_EPZ IN(SELECT EPZ.ID_EPZ FROM EvidencijaProizvodnjeZag EPZ WHERE EPZ.BrojRN IN((SELECT NS1.BrojRN4 FROM NarudzbeSta NS1 WHERE NS1.ID_NarZ = NarZ.ID_NarZ AND NS1.BazniRN = 1 AND NS1.Obrada4 = 1 AND NS1.Isporuceno = 0 AND NS1.PozicijaKupac = TJ.PozicijaKupac AND ISNULL(NS1.BrojRN4, '') <> '' ))) AND EPS.Status = 1), 0) AS Fakturirano 
	FROM TmpJanjic TJ
		LEFT JOIN NarudzbeZag NarZ ON TJ.OrderNo = NarZ.OrderNo 
	WHERE TJ.VrstaDok = 'Order'
UNION
SELECT TJ.*, 0, 0 
	FROM TmpJanjic TJ
		LEFT JOIN NarudzbeZag NarZ ON TJ.OrderNo = NarZ.OrderNo 
	WHERE TJ.VrstaDok IS NULL
	ORDER BY TJ.ID


