     use rfind
	 select sum(komada) komada,ID_Par
	 from(
select case when zavrsnaobrada='Tokarenje' then spremnot_pro
            when zavrsnaobrada='Kaljenje' then  spremnok_pro
			when zavrsnaobrada='Tvrdo tokarenje' then spremnott_pro
			when zavrsnaobrada='Brušenje' then spremnobr_pro
			end komada,id_par
from(
      SELECT feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Par,feroapp.dbo.StanjeProizvodnjeListPrepak.Bazni_RN, (SELECT feroapp.dbo.StanjeProizvodnjeListPrepak.OrderNo FROM feroapp.dbo.StanjeProizvodnjeListPrepak WHERE feroapp.dbo.StanjeProizvodnjeListPrepak.BrojRN = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Narudzba, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Mat, 
      (SELECT NarudzbeSta.ID_NarZ FROM NarudzbeSta WHERE NarudzbeSta.BrojRN = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS NarudzbaFull, 
      (SELECT Proizvodi.NazivPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_K WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_T END)) AS Proizvod, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.BaznaObrada, feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada, feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoT_Pak, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeT_kg, feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoK_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoK_Pak, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeK_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeK_kg, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje , feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoTT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoTT_Pak, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeTT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeTT_kg, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje , feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoBR_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoBR_Pak, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeBR_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeBR_kg, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.KolicinaNar, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoK_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoTT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoBR_Pro, 
      ISNULL((SELECT Proizvodi.TezinaPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_K WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_T END)),0) AS TezinaProKom, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.VlasnistvoFX, 
      (SELECT EvidencijaProizvodnjeZag.BrojKomadaPoPakiranju FROM EvidencijaProizvodnjeZag WHERE EvidencijaProizvodnjeZag.BrojRN = (CASE feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS BrojKomadaPoPakiranju, 
      (SELECT max(s.datum) FROM [FeroApp].[dbo].[EvidencijaProizvodnjeZag] z left join EvidencijaProizvodnjeSta s on s.ID_EPZ=z.ID_EPZ where BrojRN = (CASE feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Datumproizvodnje, 
      DatumIsporuke 
      FROM feroapp.dbo.StanjeProizvodnjeListPrepak('Prsteni', 'Neisporuceno', 0) 
      --WHERE feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Par = 274 
      where (feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoT_Pro <> 0 OR feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoK_Pro <> 0 OR feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoTT_Pro <> 0 OR feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoBR_Pro <> 0) 
      UNION ALL
      SELECT feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Par,feroapp.dbo.StanjeProizvodnjeListPrepak.Bazni_RN, (SELECT feroapp.dbo.StanjeProizvodnjeListPrepak.OrderNo FROM feroapp.dbo.StanjeProizvodnjeListPrepak WHERE feroapp.dbo.StanjeProizvodnjeListPrepak.BrojRN = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Narudzba, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Mat, 
      (SELECT NarudzbeSta.ID_NarZ FROM NarudzbeSta WHERE NarudzbeSta.BrojRN = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS NarudzbaFull, 
      (SELECT Proizvodi.NazivPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_K WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_T END)) AS Proizvod, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.BaznaObrada, feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada, feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoT_Pak, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeT_kg, feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoK_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoK_Pak, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeK_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeK_kg, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje , feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoTT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoTT_Pak, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeTT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeTT_kg, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje , feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoBR_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoBR_Pak, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeBR_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.PakiranjeBR_kg, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.KolicinaNar, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoK_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoTT_Pro, feroapp.dbo.StanjeProizvodnjeListPrepak.IsporucenoBR_Pro, 
      ISNULL((SELECT Proizvodi.TezinaPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_K WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Pro_T END)),0) AS TezinaProKom, 
      feroapp.dbo.StanjeProizvodnjeListPrepak.VlasnistvoFX, 
      (SELECT EvidencijaProizvodnjeZag.BrojKomadaPoPakiranju FROM EvidencijaProizvodnjeZag WHERE EvidencijaProizvodnjeZag.BrojRN = (CASE feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS BrojKomadaPoPakiranju, 
      (SELECT max(s.datum) FROM [FeroApp].[dbo].[EvidencijaProizvodnjeZag] z left join EvidencijaProizvodnjeSta s on s.ID_EPZ=z.ID_EPZ where BrojRN = (CASE feroapp.dbo.StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE feroapp.dbo.StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Datumproizvodnje, 
      DatumIsporuke 
      FROM feroapp.dbo.StanjeProizvodnjeListPrepak('Prsteni', 'Neisporuceno', 1) 
      --WHERE feroapp.dbo.StanjeProizvodnjeListPrepak.ID_Par = 274 
      where (feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoT_Pro <> 0 OR feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoK_Pro <> 0 OR feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoTT_Pro <> 0 OR feroapp.dbo.StanjeProizvodnjeListPrepak.SpremnoBR_Pro <> 0) 
	  ) x1
      --ORDER BY feroapp.dbo.StanjeProizvodnjeListPrepak.VlasnistvoFX, Proizvod
	  )x2
	  group by id_par
       