 USE FEROAPP
	  SELECT StanjeProizvodnjeListPrepak.Bazni_RN, (SELECT NarudzbeDetaljnoView.OrderNo FROM NarudzbeDetaljnoView WHERE NarudzbeDetaljnoView.BrojRN = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Narudzba,  
       StanjeProizvodnjeListPrepak.ID_Mat,  
       (SELECT NarudzbeSta.ID_NarZ FROM NarudzbeSta WHERE NarudzbeSta.BrojRN = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS NarudzbaFull,  
       (SELECT Proizvodi.NazivPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_K WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE StanjeProizvodnjeListPrepak.ID_Pro_T END)) AS Proizvod,  
       StanjeProizvodnjeListPrepak.BaznaObrada, StanjeProizvodnjeListPrepak.ZavrsnaObrada, StanjeProizvodnjeListPrepak.RN_Tokarenje, StanjeProizvodnjeListPrepak.SpremnoT_Pro, StanjeProizvodnjeListPrepak.SpremnoT_Pak,  
       StanjeProizvodnjeListPrepak.PakiranjeT_Pro, StanjeProizvodnjeListPrepak.PakiranjeT_kg, StanjeProizvodnjeListPrepak.RN_Kaljenje, StanjeProizvodnjeListPrepak.SpremnoK_Pro, StanjeProizvodnjeListPrepak.SpremnoK_Pak,  
       StanjeProizvodnjeListPrepak.PakiranjeK_Pro, StanjeProizvodnjeListPrepak.PakiranjeK_kg,  
       StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje , StanjeProizvodnjeListPrepak.SpremnoTT_Pro, StanjeProizvodnjeListPrepak.SpremnoTT_Pak, StanjeProizvodnjeListPrepak.PakiranjeTT_Pro, StanjeProizvodnjeListPrepak.PakiranjeTT_kg,  
       StanjeProizvodnjeListPrepak.RN_Brusenje , StanjeProizvodnjeListPrepak.SpremnoBR_Pro, StanjeProizvodnjeListPrepak.SpremnoBR_Pak, StanjeProizvodnjeListPrepak.PakiranjeBR_Pro, StanjeProizvodnjeListPrepak.PakiranjeBR_kg,  
       StanjeProizvodnjeListPrepak.KolicinaNar, StanjeProizvodnjeListPrepak.IsporucenoT_Pro, StanjeProizvodnjeListPrepak.IsporucenoK_Pro, StanjeProizvodnjeListPrepak.IsporucenoTT_Pro, StanjeProizvodnjeListPrepak.IsporucenoBR_Pro,  
       ISNULL((SELECT Proizvodi.TezinaPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_K WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE StanjeProizvodnjeListPrepak.ID_Pro_T END)),0) AS TezinaProKom,  
       StanjeProizvodnjeListPrepak.VlasnistvoFX,  
       (SELECT EvidencijaProizvodnjeZag.BrojKomadaPoPakiranju FROM EvidencijaProizvodnjeZag WHERE EvidencijaProizvodnjeZag.BrojRN = (CASE StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS BrojKomadaPoPakiranju,  
       (SELECT max(s.datum) FROM [FeroApp].[dbo].[EvidencijaProizvodnjeZag] z left join EvidencijaProizvodnjeSta s on s.ID_EPZ=z.ID_EPZ where BrojRN = (CASE StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Datumproizvodnje,  
       DatumIsporuke  
       FROM StanjeProizvodnjeListPrepak('Prsteni', 'Neisporuceno', 0)  
       WHERE StanjeProizvodnjeListPrepak.ID_Par = 221452   
       AND (StanjeProizvodnjeListPrepak.SpremnoT_Pro <> 0 OR StanjeProizvodnjeListPrepak.SpremnoK_Pro <> 0 OR StanjeProizvodnjeListPrepak.SpremnoTT_Pro <> 0 OR StanjeProizvodnjeListPrepak.SpremnoBR_Pro <> 0) 
	   UNION ALL  
       SELECT StanjeProizvodnjeListPrepak.Bazni_RN, (SELECT NarudzbeDetaljnoView.OrderNo FROM NarudzbeDetaljnoView WHERE NarudzbeDetaljnoView.BrojRN = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Narudzba,  
       StanjeProizvodnjeListPrepak.ID_Mat,  
       (SELECT NarudzbeSta.ID_NarZ FROM NarudzbeSta WHERE NarudzbeSta.BrojRN = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS NarudzbaFull,  
       (SELECT Proizvodi.NazivPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_K WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE StanjeProizvodnjeListPrepak.ID_Pro_T END)) AS Proizvod,  
       StanjeProizvodnjeListPrepak.BaznaObrada, StanjeProizvodnjeListPrepak.ZavrsnaObrada, StanjeProizvodnjeListPrepak.RN_Tokarenje, StanjeProizvodnjeListPrepak.SpremnoT_Pro, StanjeProizvodnjeListPrepak.SpremnoT_Pak,  
       StanjeProizvodnjeListPrepak.PakiranjeT_Pro, StanjeProizvodnjeListPrepak.PakiranjeT_kg, StanjeProizvodnjeListPrepak.RN_Kaljenje, StanjeProizvodnjeListPrepak.SpremnoK_Pro, StanjeProizvodnjeListPrepak.SpremnoK_Pak,  
       StanjeProizvodnjeListPrepak.PakiranjeK_Pro, StanjeProizvodnjeListPrepak.PakiranjeK_kg,  
       StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje , StanjeProizvodnjeListPrepak.SpremnoTT_Pro, StanjeProizvodnjeListPrepak.SpremnoTT_Pak, StanjeProizvodnjeListPrepak.PakiranjeTT_Pro, StanjeProizvodnjeListPrepak.PakiranjeTT_kg,  
       StanjeProizvodnjeListPrepak.RN_Brusenje , StanjeProizvodnjeListPrepak.SpremnoBR_Pro, StanjeProizvodnjeListPrepak.SpremnoBR_Pak, StanjeProizvodnjeListPrepak.PakiranjeBR_Pro, StanjeProizvodnjeListPrepak.PakiranjeBR_kg,  
       StanjeProizvodnjeListPrepak.KolicinaNar, StanjeProizvodnjeListPrepak.IsporucenoT_Pro, StanjeProizvodnjeListPrepak.IsporucenoK_Pro, StanjeProizvodnjeListPrepak.IsporucenoTT_Pro, StanjeProizvodnjeListPrepak.IsporucenoBR_Pro,  
       ISNULL((SELECT Proizvodi.TezinaPro FROM Proizvodi WHERE Proizvodi.ID_Pro = (CASE WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Kaljenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_K WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_TT WHEN StanjeProizvodnjeListPrepak.ZavrsnaObrada = 'Brusenje' THEN StanjeProizvodnjeListPrepak.ID_Pro_BR ELSE StanjeProizvodnjeListPrepak.ID_Pro_T END)),0) AS TezinaProKom,  
       StanjeProizvodnjeListPrepak.VlasnistvoFX,  
       (SELECT EvidencijaProizvodnjeZag.BrojKomadaPoPakiranju FROM EvidencijaProizvodnjeZag WHERE EvidencijaProizvodnjeZag.BrojRN = (CASE StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS BrojKomadaPoPakiranju,  
       (SELECT max(s.datum) FROM [FeroApp].[dbo].[EvidencijaProizvodnjeZag] z left join EvidencijaProizvodnjeSta s on s.ID_EPZ=z.ID_EPZ where BrojRN = (CASE StanjeProizvodnjeListPrepak.ZavrsnaObrada WHEN 'Brusenje' THEN StanjeProizvodnjeListPrepak.RN_Brusenje WHEN 'Tvrdo tokarenje' THEN StanjeProizvodnjeListPrepak.RN_TvrdoTokarenje WHEN 'Kaljenje' THEN StanjeProizvodnjeListPrepak.RN_Kaljenje ELSE StanjeProizvodnjeListPrepak.RN_Tokarenje END)) AS Datumproizvodnje,  
       DatumIsporuke  
       FROM StanjeProizvodnjeListPrepak('Prsteni', 'Neisporuceno', 1)  
       WHERE StanjeProizvodnjeListPrepak.ID_Par = 221452  
       AND (StanjeProizvodnjeListPrepak.SpremnoT_Pro <> 0 OR StanjeProizvodnjeListPrepak.SpremnoK_Pro <> 0 OR StanjeProizvodnjeListPrepak.SpremnoTT_Pro <> 0 OR StanjeProizvodnjeListPrepak.SpremnoBR_Pro <> 0)       
       ORDER BY StanjeProizvodnjeListPrepak.VlasnistvoFX, Proizvod